#!/usr/bin/env python3
"""Emit the per-token UPDATEs for hls-fix.sql from the two pin results.

  python3 gen-token-sql.py > hls-fix-tokens.sql

Inputs (relative to the status repo root):
  ops/3435-hls-fix/rewilded-metadata-fix/result.csv    edition,token_id,old_metadata_cid,new_metadata_cid  (ETH, 50 rows)
  ops/3435-hls-fix/feralverse-metadata-fix/result.csv  token_id,old_metadata_cid,new_metadata_cid          (Tezos, 142 rows)
"""
import csv, os, re, sys
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
CID = re.compile(r'^(Qm[1-9A-HJ-NP-Za-km-z]{44}|bafy[a-z2-7]{55,})$')
ETH = '0xaDB387798599f5777CD0531c2ECb36007C1D1a51'

def rows(p):
    p = os.path.join(root, p)
    if not os.path.exists(p): sys.exit(f'missing {p} — run its pin.sh first')
    r = list(csv.DictReader(open(p)))
    for x in r:
        if not x['token_id'].isdigit() or not CID.match(x['new_metadata_cid']) or not CID.match(x['old_metadata_cid']):
            sys.exit(f'bad row in {p}: {x}')
    return r

eth = rows('ops/3435-hls-fix/rewilded-metadata-fix/result.csv')
tz  = rows('ops/3435-hls-fix/feralverse-metadata-fix/result.csv')
print(f'-- generated by gen-token-sql.py: {len(eth)} ETH swaps rows, {len(tz)} Tezos artworks rows')
print('-- 3a · ETH (Rewilded Topography #1): swaps.ipfs_cid = metadata directory CID (API serves <cid>/metadata.json)')
print('--      the WHERE also pins the OLD cid, so a row updated already or pointing elsewhere is skipped, not clobbered')
for r in eth:
    print(f"UPDATE swaps SET ipfs_cid = '{r['new_metadata_cid']}', updated_at = now() "
          f"WHERE contract_address = '{ETH}' AND token = '{r['token_id']}' AND status = 'complete' AND ipfs_cid = '{r['old_metadata_cid']}';")
print(f"-- expect UPDATE 1 × {len(eth)}")
print('-- 3b · Tezos (FeralVerse): artworks.metadata.ipfs_cid = TZIP-21 JSON CID (what tasks/tezos_metadata.go would persist)')
for r in tz:
    print(f"UPDATE artworks SET metadata = metadata || jsonb_build_object('ipfs_cid', '{r['new_metadata_cid']}'), updated_at = now() "
          f"WHERE id = '{r['token_id']}' AND series_id IN ('506e46e1-fe84-41eb-b72c-11420b3fda23','45c0f2cc-eef6-43db-87a3-f9a51275e0ec');")
print(f"-- expect UPDATE 1 × {len(tz)}")
