#!/usr/bin/env python3
"""swaps.ipfs_cid UPDATEs from pin.sh's result.csv (after the chain updates are
confirmed with `update-token-uri.mjs check`).

  python3 gen-sql.py [result.csv] > swaps-update.sql

token = the DB's own form (token_id_db: decimal, or 64-hex for a few older swaps).
Each UPDATE also pins the OLD cid in its WHERE, so a row already updated or
pointing elsewhere is skipped, never clobbered. Expect UPDATE 1 per row.
"""
import csv, re, sys
CID = re.compile(r'^(Qm[1-9A-HJ-NP-Za-km-z]{44}|bafy[a-z2-7]{55,})$')
rows = list(csv.DictReader(open(sys.argv[1] if len(sys.argv) > 1 else 'result.csv')))
for r in rows:
    r['token_id_db'] = r.get('token_id_db') or r['token_id']
    r['db_cid'] = r.get('db_cid') or r['old_metadata_cid']   # swaps.ipfs_cid may differ from the chain's cid (regenerated metadata); WHERE must use the DB's value
    if not re.fullmatch(r'\d+|[0-9a-fA-F]{64}', r['token_id_db']) or not CID.match(r['db_cid']) or not CID.match(r['new_metadata_cid']) or not re.match(r'^0x[0-9a-f]{40}$', r['contract']): sys.exit(f'bad row {r}')
print(f'-- generated by v2-metadata-regen/gen-sql.py: {len(rows)} swaps rows; run inside a transaction and check the count')
print('BEGIN;')
for r in rows:
    print(f"UPDATE swaps SET ipfs_cid = '{r['new_metadata_cid']}', updated_at = now() "
          f"WHERE lower(contract_address) = '{r['contract']}' AND token = '{r['token_id_db']}' AND status = 'complete' AND ipfs_cid = '{r['db_cid']}';")
print(f'-- expect UPDATE 1 × {len(rows)}')
print('-- artworks.metadata.ipfs_cid: only rows where it still carries the OLD on-chain cid (a 2025-12 regeneration wrote it there for 25 Primordium tokens); others are untouched')
for r in rows:
    print(f"UPDATE artworks SET metadata = metadata || jsonb_build_object('ipfs_cid', '{r['new_metadata_cid']}'), updated_at = now() "
          f"WHERE id IN (SELECT artwork_id FROM swaps WHERE lower(contract_address) = '{r['contract']}' AND token = '{r['token_id_db']}' AND status = 'complete') "
          f"AND metadata->>'ipfs_cid' = '{r['old_metadata_cid']}';")
print('-- expect UPDATE 0 or 1 each; then COMMIT (or ROLLBACK)')
