-- HLS fix — Feral File DB side (feral-file/feral-file#3435)
-- Run AFTER the on-chain updates (tools/update-token-uri, tools/update-tezos-metadata)
-- so chain and DB flip together. Everything is inside one transaction; the
-- final SELECTs show the result — COMMIT only if they look right.
--
-- What each table does (feral-file-server):
--   ipfs_reference(uri, ipfs_uri)   artworks.preview_uri (CDN path) -> ipfs:// URI.
--                                   Read by every metadata generator (swap mint,
--                                   Tezos mint/refresh, OpenSea refresh) as
--                                   animation_url / artifactUri.
--   swaps.ipfs_cid                  V2 ETH tokens: GET /api/contracts/:c/tokens/:t
--                                   fetches <ipfs_cid>/metadata.json from IPFS at
--                                   request time — the API does not store animation_url.
--   artworks.metadata->>'ipfs_cid'  Tezos tokens: CID of the TZIP-21 JSON the
--                                   server last pushed on-chain (tasks/tezos_metadata.go).
--   artworks.preview_mime_type      currently 'application/x-mpegurl' for these series.

BEGIN;

-- 0 · before
SELECT uri, ipfs_uri FROM ipfs_reference WHERE uri IN (
  'previews/7b77f5d5-fefc-4a77-a40c-e9e8e5f8f9cb/1679631642/preview.mp4',
  'previews/506e46e1-fe84-41eb-b72c-11420b3fda23/1680573925/preview.mp4',
  'previews/45c0f2cc-eef6-43db-87a3-f9a51275e0ec/1680599651/preview.mp4');

-- 1 · preview file -> playable MP4 CID (same bytes as the CDN preview.mp4, SHA-256 verified)
INSERT INTO ipfs_reference (uri, ipfs_uri, created_at, updated_at) VALUES
  ('previews/7b77f5d5-fefc-4a77-a40c-e9e8e5f8f9cb/1679631642/preview.mp4', 'ipfs://QmV6a8NCQDTq1pMddqgMNg9xutBkp7oa2EJTspi5tH7z6C', now(), now()),
  ('previews/506e46e1-fe84-41eb-b72c-11420b3fda23/1680573925/preview.mp4', 'ipfs://bafybeiagkwrb4av4e27x2fihhwl3q3oa5uqp42wynjd5vksfiswouz4tka', now(), now()),
  ('previews/45c0f2cc-eef6-43db-87a3-f9a51275e0ec/1680599651/preview.mp4', 'ipfs://bafybeifu35t24hzfbq7voe5n3xe4sbclckrs6vsn2b5xixtv3togk4yi2u', now(), now())
ON CONFLICT (uri) DO UPDATE SET ipfs_uri = EXCLUDED.ipfs_uri, updated_at = now();

-- 2 · mime type of the preview file for the three series
UPDATE artworks SET preview_mime_type = 'video/mp4', updated_at = now()
WHERE series_id IN ('7b77f5d5-fefc-4a77-a40c-e9e8e5f8f9cb',
                    '506e46e1-fe84-41eb-b72c-11420b3fda23',
                    '45c0f2cc-eef6-43db-87a3-f9a51275e0ec')
  AND preview_mime_type = 'application/x-mpegurl';
-- expect: 101 + 71 + 71 = 243 rows (Rewilded incl. the 47 still-on-Bitmark editions; the file is the same)

-- 3 · per-token pointers — generated from the pin results, see hls-fix-tokens.sql
--     (python3 gen-token-sql.py > hls-fix-tokens.sql). Paste it here, or \i it.
\i hls-fix-tokens.sql   -- (this file, generated by tools/db-sql/gen-token-sql.py; applied 2026-08-25)

-- 4 · after
SELECT uri, ipfs_uri FROM ipfs_reference WHERE uri IN (
  'previews/7b77f5d5-fefc-4a77-a40c-e9e8e5f8f9cb/1679631642/preview.mp4',
  'previews/506e46e1-fe84-41eb-b72c-11420b3fda23/1680573925/preview.mp4',
  'previews/45c0f2cc-eef6-43db-87a3-f9a51275e0ec/1680599651/preview.mp4');

SELECT s.artwork_index, s.token, s.ipfs_cid
FROM swaps s WHERE s.contract_address = '0xaDB387798599f5777CD0531c2ECb36007C1D1a51' AND s.status = 'complete'
ORDER BY s.artwork_index;                           -- 54 rows; 50 should carry the new CIDs

SELECT count(*) FILTER (WHERE metadata->>'ipfs_cid' IS NOT NULL) AS with_cid, count(*) AS total
FROM artworks WHERE series_id IN ('506e46e1-fe84-41eb-b72c-11420b3fda23','45c0f2cc-eef6-43db-87a3-f9a51275e0ec');  -- 142 / 142

-- ROLLBACK;   -- if anything above is off
COMMIT;
